### ISSUE TITLE
Property 'forRoot' does not exist on type 'TwilioModule'

### ISSUE THREAD

**Issue by jmopaso** [rejvban/nestjs-twilio#42]
# Bug Report

## Describe the Bug

Hi! I am trying to integrate the library in the current version `v3.1.0` but on registering the module exactly as recommended in the getting started documentation i receive the following error `Property 'forRootAsync' does not exist on type 'typeof TwilioModule'`

## How to Reproduce

Just follow the library documentation with the register module example:

![Screen Shot 2022-10-14 at 13 44 49](https://user-images.githubusercontent.com/30938880/195899110-b683f228-227d-4930-b5e4-97b30fafe6f4.png)

## My Environment

- OS: macOS
- Version of nestjs-twilio: v3.1.0

**Comment by lkaric** [comment]
What version of Nestjs are you using?

**Comment by jmopaso** [comment]
I'm using this nest dependencies 
```
"@nestjs/common": "^8.0.0",
"@nestjs/config": "^2.2.0",
"@nestjs/core": "^8.0.0",
"@nestjs/cli": "^8.0.0",
```

**Comment by lkaric** [comment]
Alright, the package utilises a configurable module builder introduced with v9 of Nestjs.

Hotfix solutions (I recommend the 1st one):
1. Upgrade Nestjs dependencies.
2. Use a lesser major version of the package. 

I'll try and decouple the versions when I get some free time,
