### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof TwilioModule'

### ISSUE THREAD

**Issue by Dubask** [rejvban/nestjs-twilio#45]
# Bug Report

## Describe the Bug
Getting Property 'forRoot' does not exist on type 'typeof TwilioModule'

## How to Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
just add the twilioModule.forRoot....

## Expected Behavior
forRoot will not give an ts error
<img width="431" alt="Screen Shot 2022-12-01 at 21 07 17" src="https://user-images.githubusercontent.com/30698018/205138773-83989268-d4b8-4693-beec-680b08b663e1.png">

Tell me what should happen.

## Error

Error resulted by the potential bug.

## Your Environment
mac, vscode
- Version of nestjs-twilio: 3.2.0

## Error reproducing steps

Please explain how did your error ocurr, you can also leave gists, repos or any kind of codebase.

## Additional Information

Any other information about the problem here.

**Comment by lkaric** [comment]
@Dubask What version of Nestjs are you on?

**Comment by thezeeshantariq** [comment]
Facing the same issue: here is version info from package.json

`
 "@nestjs-modules/mailer": "^1.7.1",
"@nestjs/common": "^8.0.0",
"@nestjs/config": "^2.1.0",
"@nestjs/core": "^8.0.0",
`

and the version of `nestjs-twilio: 3.2.0`

**Comment by lkaric** [comment]
@thezeeshantariq @Dubask Please read through https://github.com/rejvban/nestjs-twilio/issues/42, the issue is the same probably for both of you. I made a note to add this to the documentation
