### ISSUE TITLE
How can I generate a client token using nestjs-twilio?

### ISSUE THREAD

**Issue by alexis1111** [rejvban/nestjs-twilio#57]
i can't find a way to generate a token like this ```const AccessToken = require('twilio').jwt.AccessToken;```, this appears on the twilio api docs but not here :/

**Comment by lkaric** [comment]
This is just a general wrapper around the Twilio SDK, I'm willing to try and help you with the issue, but I'll need more context.

**Comment by alexis1111** [comment]
> This is just a general wrapper around the Twilio SDK, I'm willing to try and help you with the issue, but I'll need more context.

Sure! i need to generate a token to grant access to the video feature on the client app, im using the following code

```
async generateToken(user: string): Promise<any> {
    const AccessToken = twilio.jwt.AccessToken;
    const VideoGrant = AccessToken.VideoGrant;

    const grant = new VideoGrant({
      room: 'test-room',
    });

    const token = new AccessToken(
      process.env.TWILIO_ACCOUNT_SID,
      process.env.TWILIO_API_KEY,
      process.env.TWILIO_API_SECRET,
      { identity: user },
    );

    token.addGrant(grant);

    return { 'twilio-token': token.toJwt() };
  }
  ```
  
  im using twilio directly like this `import * as twilio from 'twilio';`, but it would be nice to just use `this.twilioService.jwt.AccessToken`
  
  thank you so much for replying!
