### ISSUE TITLE
Can I register multiple Twillio accounts in one app?

### ISSUE THREAD

**Issue by ZhaoKunLong** [rejvban/nestjs-twilio#61]
# Help wanted
Can I register multiple Twillio accounts in one app? What should I do?

# Case
This is my case.
-  I have a platform to serve different customers.
- I need to send different information to different customers on the platform. However, each customer wants to use their own Twilio account for independent billing.
- How should I deal with such a situation? 
- How to dynamically load the Twilio account and ID under the user account from the database and send information according to different user requests when the app is running?

**Comment by lkaric** [comment]
@ZhaoKunLong Considering I'm cleaning up, might as well give you some directions. The question you posted is more related to the Nest itself. I'd explore option of altering [injection scopes](https://docs.nestjs.com/fundamentals/injection-scopes) and making a dynamic provider.
